package com.beetron.outmall.models;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.beetron.outmall.models.ProCategory;
import com.beetron.outmall.models.ProSummary;

import com.beetron.outmall.models.ProCategoryDao;
import com.beetron.outmall.models.ProSummaryDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig proCategoryDaoConfig;
    private final DaoConfig proSummaryDaoConfig;

    private final ProCategoryDao proCategoryDao;
    private final ProSummaryDao proSummaryDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        proCategoryDaoConfig = daoConfigMap.get(ProCategoryDao.class).clone();
        proCategoryDaoConfig.initIdentityScope(type);

        proSummaryDaoConfig = daoConfigMap.get(ProSummaryDao.class).clone();
        proSummaryDaoConfig.initIdentityScope(type);

        proCategoryDao = new ProCategoryDao(proCategoryDaoConfig, this);
        proSummaryDao = new ProSummaryDao(proSummaryDaoConfig, this);

        registerDao(ProCategory.class, proCategoryDao);
        registerDao(ProSummary.class, proSummaryDao);
    }
    
    public void clear() {
        proCategoryDaoConfig.getIdentityScope().clear();
        proSummaryDaoConfig.getIdentityScope().clear();
    }

    public ProCategoryDao getProCategoryDao() {
        return proCategoryDao;
    }

    public ProSummaryDao getProSummaryDao() {
        return proSummaryDao;
    }

}
