package com.beetron.outmall.models;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "PRO_CATEGORY".
 */
public class ProCategory {

    private String id;
    private String name;
    private String stank;

    // KEEP FIELDS - put your custom fields here
    private int count;
    private boolean isSelected = false;
    // KEEP FIELDS END

    public ProCategory() {
    }

    public ProCategory(String id, String name, String stank) {
        this.id = id;
        this.name = name;
        this.stank = stank;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getStank() {
        return stank;
    }

    public void setStank(String stank) {
        this.stank = stank;
    }

    // KEEP METHODS - put your custom methods here

    public int getCount() {
        return count;
    }

    public void setCount(int count) {
        this.count = count;
    }

    public boolean isSelected() {
        return isSelected;
    }

    public void setIsSelected(boolean isSelected) {

        this.isSelected = isSelected;
    }

// KEEP METHODS END

}
