package com.beetron.outmall.models;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "PRO_SUMMARY".
 */
public class ProSummary {

    private String sid;
    private String fid;
    private String title;
    private String jianshu;
    private String img;
    private String price1;
    private String price2;
    private String xl;

    // KEEP FIELDS - put your custom fields here
    private int count = 0;
    // KEEP FIELDS END

    public ProSummary() {
    }

    public ProSummary(String sid, String fid, String title, String jianshu, String img, String price1, String price2, String xl) {
        this.sid = sid;
        this.fid = fid;
        this.title = title;
        this.jianshu = jianshu;
        this.img = img;
        this.price1 = price1;
        this.price2 = price2;
        this.xl = xl;
    }

    public String getSid() {
        return sid;
    }

    public void setSid(String sid) {
        this.sid = sid;
    }

    public String getFid() {
        return fid;
    }

    public void setFid(String fid) {
        this.fid = fid;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getJianshu() {
        return jianshu;
    }

    public void setJianshu(String jianshu) {
        this.jianshu = jianshu;
    }

    public String getImg() {
        return img;
    }

    public void setImg(String img) {
        this.img = img;
    }

    public String getPrice1() {
        return price1;
    }

    public void setPrice1(String price1) {
        this.price1 = price1;
    }

    public String getPrice2() {
        return price2;
    }

    public void setPrice2(String price2) {
        this.price2 = price2;
    }

    public String getXl() {
        return xl;
    }

    public void setXl(String xl) {
        this.xl = xl;
    }

    // KEEP METHODS - put your custom methods here

    public int getCount() {
        return count;
    }

    public void setCount(int count) {
        this.count = count;
    }

    // KEEP METHODS END

}
