package com.beetron.outmall.models;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "USER_INFO_MODEL".
 */
public class UserInfoModel {

    /** Not-null value. */
    private String uid;
    private String mail;
    private String sex;
    private String nickname;
    private String headimg;
    private String uname;
    private String dengji;
    private String tel;
    private String upass;
    private String city;
    private String unid;
    private String area;
    private String refer;
    private String address;
    private String province;
    private String openid;
    private String jifen;
    private String cunkuan;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public UserInfoModel() {
    }

    public UserInfoModel(String uid) {
        this.uid = uid;
    }

    public UserInfoModel(String uid, String mail, String sex, String nickname, String headimg, String uname, String dengji, String tel, String upass, String city, String unid, String area, String refer, String address, String province, String openid, String jifen, String cunkuan) {
        this.uid = uid;
        this.mail = mail;
        this.sex = sex;
        this.nickname = nickname;
        this.headimg = headimg;
        this.uname = uname;
        this.dengji = dengji;
        this.tel = tel;
        this.upass = upass;
        this.city = city;
        this.unid = unid;
        this.area = area;
        this.refer = refer;
        this.address = address;
        this.province = province;
        this.openid = openid;
        this.jifen = jifen;
        this.cunkuan = cunkuan;
    }

    /** Not-null value. */
    public String getUid() {
        return uid;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUid(String uid) {
        this.uid = uid;
    }

    public String getMail() {
        return mail;
    }

    public void setMail(String mail) {
        this.mail = mail;
    }

    public String getSex() {
        return sex;
    }

    public void setSex(String sex) {
        this.sex = sex;
    }

    public String getNickname() {
        return nickname;
    }

    public void setNickname(String nickname) {
        this.nickname = nickname;
    }

    public String getHeadimg() {
        return headimg;
    }

    public void setHeadimg(String headimg) {
        this.headimg = headimg;
    }

    public String getUname() {
        return uname;
    }

    public void setUname(String uname) {
        this.uname = uname;
    }

    public String getDengji() {
        return dengji;
    }

    public void setDengji(String dengji) {
        this.dengji = dengji;
    }

    public String getTel() {
        return tel;
    }

    public void setTel(String tel) {
        this.tel = tel;
    }

    public String getUpass() {
        return upass;
    }

    public void setUpass(String upass) {
        this.upass = upass;
    }

    public String getCity() {
        return city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    public String getUnid() {
        return unid;
    }

    public void setUnid(String unid) {
        this.unid = unid;
    }

    public String getArea() {
        return area;
    }

    public void setArea(String area) {
        this.area = area;
    }

    public String getRefer() {
        return refer;
    }

    public void setRefer(String refer) {
        this.refer = refer;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public String getProvince() {
        return province;
    }

    public void setProvince(String province) {
        this.province = province;
    }

    public String getOpenid() {
        return openid;
    }

    public void setOpenid(String openid) {
        this.openid = openid;
    }

    public String getJifen() {
        return jifen;
    }

    public void setJifen(String jifen) {
        this.jifen = jifen;
    }

    public String getCunkuan() {
        return cunkuan;
    }

    public void setCunkuan(String cunkuan) {
        this.cunkuan = cunkuan;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
